--
-- Drop tables
--

DROP TABLE CMS_LOG_VISITE          CASCADE CONSTRAINTS PURGE;

DROP TABLE CMS_PAGINE_COMP         CASCADE CONSTRAINTS PURGE;
DROP TABLE CMS_PAGINE_ARTICOLI     CASCADE CONSTRAINTS PURGE;
DROP TABLE CMS_PAGINE_DESC         CASCADE CONSTRAINTS PURGE;
DROP TABLE CMS_PAGINE              CASCADE CONSTRAINTS PURGE;
DROP TABLE CMS_TIPI_PAGINA         CASCADE CONSTRAINTS PURGE;

DROP TABLE CMS_ARTICOLI_PREZZI     CASCADE CONSTRAINTS PURGE;
DROP TABLE CMS_ARTICOLI_COMP       CASCADE CONSTRAINTS PURGE;
DROP TABLE CMS_ARTICOLI_CORR       CASCADE CONSTRAINTS PURGE;
DROP TABLE CMS_ARTICOLI_TAG        CASCADE CONSTRAINTS PURGE;
DROP TABLE CMS_ARTICOLI_MULT       CASCADE CONSTRAINTS PURGE;
DROP TABLE CMS_ARTICOLI_CONT       CASCADE CONSTRAINTS PURGE;
DROP TABLE CMS_ARTICOLI_LUOGHI     CASCADE CONSTRAINTS PURGE;
DROP TABLE CMS_ARTICOLI_AUT        CASCADE CONSTRAINTS PURGE;
DROP TABLE CMS_ARTICOLI            CASCADE CONSTRAINTS PURGE;

DROP TABLE CMS_TIPI_ARTICOLO_DESC  CASCADE CONSTRAINTS PURGE;
DROP TABLE CMS_TIPI_ARTICOLO       CASCADE CONSTRAINTS PURGE;
DROP TABLE CMS_SOTTOCATEGORIE_DESC CASCADE CONSTRAINTS PURGE;
DROP TABLE CMS_SOTTOCATEGORIE      CASCADE CONSTRAINTS PURGE;
DROP TABLE CMS_CATEGORIE_DESC      CASCADE CONSTRAINTS PURGE;
DROP TABLE CMS_CATEGORIE           CASCADE CONSTRAINTS PURGE;
DROP TABLE CMS_TAG_DESC            CASCADE CONSTRAINTS PURGE;
DROP TABLE CMS_TAG                 CASCADE CONSTRAINTS PURGE;
DROP TABLE CMS_TIPI_LUOGO_DESC     CASCADE CONSTRAINTS PURGE;
DROP TABLE CMS_TIPI_LUOGO          CASCADE CONSTRAINTS PURGE;

DROP TABLE CMS_AUTORI              CASCADE CONSTRAINTS PURGE;
DROP TABLE CMS_UTENTI              CASCADE CONSTRAINTS PURGE;
DROP TABLE CMS_LUOGHI              CASCADE CONSTRAINTS PURGE;
DROP TABLE CMS_TIPI_CONTENUTO      CASCADE CONSTRAINTS PURGE;
DROP TABLE CMS_TIPI_AUTORE         CASCADE CONSTRAINTS PURGE;
DROP TABLE CMS_TIPI_UTENTE         CASCADE CONSTRAINTS PURGE;
DROP TABLE CMS_RUOLI               CASCADE CONSTRAINTS PURGE;
DROP TABLE CMS_ISTITUTI            CASCADE CONSTRAINTS PURGE;
DROP TABLE CMS_COMUNI              CASCADE CONSTRAINTS PURGE;
DROP TABLE CMS_LINGUE              CASCADE CONSTRAINTS PURGE;

--
-- Drop sequences
--

DROP SEQUENCE SEQ_CMS_ARTICOLI_MULT;
DROP SEQUENCE SEQ_CMS_ARTICOLI;
DROP SEQUENCE SEQ_CMS_SOTTOCATEGORIE;
DROP SEQUENCE SEQ_CMS_CATEGORIE;
DROP SEQUENCE SEQ_CMS_TAG;
DROP SEQUENCE SEQ_CMS_AUTORI;
DROP SEQUENCE SEQ_CMS_UTENTI;
DROP SEQUENCE SEQ_CMS_RUOLI;
DROP SEQUENCE SEQ_CMS_LUOGHI;
DROP SEQUENCE SEQ_CMS_ISTITUTI;
DROP SEQUENCE SEQ_CMS_COMUNI;
DROP SEQUENCE SEQ_CMS_LINGUE;
DROP SEQUENCE SEQ_CMS_PAGINE;

DROP SEQUENCE SEQ_CMS_TIPI_UTENTE;
DROP SEQUENCE SEQ_CMS_TIPI_ARTICOLO;
DROP SEQUENCE SEQ_CMS_TIPI_LUOGO;
DROP SEQUENCE SEQ_CMS_TIPI_AUTORE;
DROP SEQUENCE SEQ_CMS_TIPI_CONTENUTO;
DROP SEQUENCE SEQ_CMS_TIPI_PAGINA;
