--
-- Clean Articles
--

DELETE FROM CMS_ARTICOLI_PREZZI;
DELETE FROM CMS_ARTICOLI_COMP;
DELETE FROM CMS_ARTICOLI_CORR;
DELETE FROM CMS_ARTICOLI_TAG;
DELETE FROM CMS_ARTICOLI_MULT;
DELETE FROM CMS_ARTICOLI_CONT;
DELETE FROM CMS_ARTICOLI_LUOGHI;
DELETE FROM CMS_ARTICOLI_AUT;
DELETE FROM CMS_ARTICOLI;

COMMIT;

--
-- Clean Pages
--

DELETE FROM CMS_PAGINE_DESC;
DELETE FROM CMS_PAGINE_COMP;
DELETE FROM CMS_PAGINE_ARTICOLI;
DELETE FROM CMS_PAGINE;

COMMIT;

--
-- Clean Categories
--

DELETE FROM CMS_TAG_DESC;
DELETE FROM CMS_TAG;
DELETE FROM CMS_TIPI_ARTICOLO_DESC;
DELETE FROM CMS_TIPI_ARTICOLO;
DELETE FROM CMS_SOTTOCATEGORIE_DESC;
DELETE FROM CMS_SOTTOCATEGORIE;
DELETE FROM CMS_CATEGORIE_DESC;
DELETE FROM CMS_CATEGORIE;

COMMIT;