--
-- Clean Articles
--

DELETE FROM CMS_ARTICOLI_PREZZI;
DELETE FROM CMS_ARTICOLI_COMP;
DELETE FROM CMS_ARTICOLI_CORR;
DELETE FROM CMS_ARTICOLI_TAG;
DELETE FROM CMS_ARTICOLI_MULT;
DELETE FROM CMS_ARTICOLI_CONT;
DELETE FROM CMS_ARTICOLI_LUOGHI;
DELETE FROM CMS_ARTICOLI_AUT;
DELETE FROM CMS_ARTICOLI;

COMMIT;