set define off;

INSERT INTO CMS_LINGUE(ID_LINGUA,CODICE,DESCRIZIONE,ATTIVO) VALUES (0,                      'IT', 'Italiano', 'S'); 
INSERT INTO CMS_LINGUE(ID_LINGUA,CODICE,DESCRIZIONE,ATTIVO) VALUES (SEQ_CMS_LINGUE.NEXTVAL, 'EN', 'English',  'S');
INSERT INTO CMS_LINGUE(ID_LINGUA,CODICE,DESCRIZIONE,ATTIVO) VALUES (SEQ_CMS_LINGUE.NEXTVAL, 'FR', 'Francais', 'S');
INSERT INTO CMS_LINGUE(ID_LINGUA,CODICE,DESCRIZIONE,ATTIVO) VALUES (SEQ_CMS_LINGUE.NEXTVAL, 'DE', 'Deutsche', 'S');
INSERT INTO CMS_LINGUE(ID_LINGUA,CODICE,DESCRIZIONE,ATTIVO) VALUES (SEQ_CMS_LINGUE.NEXTVAL, 'ES', 'Espanol',  'S');
COMMIT;

INSERT INTO CMS_TIPI_CONTENUTO(ID_TIPO_CONTENUTO,DESCRIZIONE,ATTIVO) VALUES (0,                              '-',         'N');
INSERT INTO CMS_TIPI_CONTENUTO(ID_TIPO_CONTENUTO,DESCRIZIONE,ATTIVO) VALUES (SEQ_CMS_TIPI_CONTENUTO.NEXTVAL, 'Video',     'S'); 
INSERT INTO CMS_TIPI_CONTENUTO(ID_TIPO_CONTENUTO,DESCRIZIONE,ATTIVO) VALUES (SEQ_CMS_TIPI_CONTENUTO.NEXTVAL, 'Immagine',  'S'); 
INSERT INTO CMS_TIPI_CONTENUTO(ID_TIPO_CONTENUTO,DESCRIZIONE,ATTIVO) VALUES (SEQ_CMS_TIPI_CONTENUTO.NEXTVAL, 'Audio',     'S'); 
INSERT INTO CMS_TIPI_CONTENUTO(ID_TIPO_CONTENUTO,DESCRIZIONE,ATTIVO) VALUES (SEQ_CMS_TIPI_CONTENUTO.NEXTVAL, 'Documento', 'S');
COMMIT;

INSERT INTO CMS_TIPI_UTENTE(ID_TIPO_UTENTE,DESCRIZIONE,ATTIVO) VALUES (0,                           'Esterno', 'S'); 
INSERT INTO CMS_TIPI_UTENTE(ID_TIPO_UTENTE,DESCRIZIONE,ATTIVO) VALUES (SEQ_CMS_TIPI_UTENTE.NEXTVAL, 'Interno', 'S');
COMMIT;

INSERT INTO CMS_AUTORI(ID_AUTORE,ID_TIPO_AUTORE COGNOME NOME) VALUES (0, 0, '-', '-'); 
COMMIT;

INSERT INTO CMS_TIPI_LUOGO(ID_TIPO_LUOGO,CODICE,ATTIVO) VALUES (0, '-', 'N');
COMMIT;

INSERT INTO CMS_LUOGHI(ID_LUOGO,ID_TIPO_LUOGO,CODICE,DESCRIZIONE,ID_COMUNE,ATTIVO) VALUES (0, 0, '-', '-', 0, 'N');
COMMIT;

INSERT INTO CMS_TIPI_PAGINA(ID_TIPO_PAGINA,DESCRIZIONE,ATTIVO) VALUES (0,                           '-',                  'N');
INSERT INTO CMS_TIPI_PAGINA(ID_TIPO_PAGINA,DESCRIZIONE,ATTIVO) VALUES (SEQ_CMS_TIPI_PAGINA.NEXTVAL, 'Pagina pubblica',    'S');
INSERT INTO CMS_TIPI_PAGINA(ID_TIPO_PAGINA,DESCRIZIONE,ATTIVO) VALUES (SEQ_CMS_TIPI_PAGINA.NEXTVAL, 'Pagina privata',     'S');
INSERT INTO CMS_TIPI_PAGINA(ID_TIPO_PAGINA,DESCRIZIONE,ATTIVO) VALUES (SEQ_CMS_TIPI_PAGINA.NEXTVAL, 'Menu intestazione',  'S');
INSERT INTO CMS_TIPI_PAGINA(ID_TIPO_PAGINA,DESCRIZIONE,ATTIVO) VALUES (SEQ_CMS_TIPI_PAGINA.NEXTVAL, 'Menu navigazione',   'S');
INSERT INTO CMS_TIPI_PAGINA(ID_TIPO_PAGINA,DESCRIZIONE,ATTIVO) VALUES (SEQ_CMS_TIPI_PAGINA.NEXTVAL, 'Menu footer',        'S');
INSERT INTO CMS_TIPI_PAGINA(ID_TIPO_PAGINA,DESCRIZIONE,ATTIVO) VALUES (SEQ_CMS_TIPI_PAGINA.NEXTVAL, 'Citazione',          'S');
INSERT INTO CMS_TIPI_PAGINA(ID_TIPO_PAGINA,DESCRIZIONE,ATTIVO) VALUES (SEQ_CMS_TIPI_PAGINA.NEXTVAL, 'Elenco singolo',     'S');
INSERT INTO CMS_TIPI_PAGINA(ID_TIPO_PAGINA,DESCRIZIONE,ATTIVO) VALUES (SEQ_CMS_TIPI_PAGINA.NEXTVAL, 'Elenco multiplo',    'S');
INSERT INTO CMS_TIPI_PAGINA(ID_TIPO_PAGINA,DESCRIZIONE,ATTIVO) VALUES (SEQ_CMS_TIPI_PAGINA.NEXTVAL, 'Elenco principale',  'S');
INSERT INTO CMS_TIPI_PAGINA(ID_TIPO_PAGINA,DESCRIZIONE,ATTIVO) VALUES (SEQ_CMS_TIPI_PAGINA.NEXTVAL, 'Elenco in evidenza', 'S');
COMMIT;

INSERT INTO CMS_PAGINE(ID_PAGINA,ID_TIPO_PAGINA,CODICE,ID_CATEGORIA,ID_SOTTOCATEGORIA,ID_TIPO_ARTICOLO,ORDINE,ATTIVO) VALUES(1,1,'HOME',0,0,0,0,'S');
INSERT INTO CMS_PAGINE(ID_PAGINA,ID_TIPO_PAGINA,CODICE,ID_CATEGORIA,ID_SOTTOCATEGORIA,ID_TIPO_ARTICOLO,ORDINE,ATTIVO) VALUES(2,1,'VIEW',0,0,0,0,'S');
COMMIT;

INSERT INTO CMS_PAGINE_DESC(ID_PAGINA,ID_LINGUA,DESCRIZIONE) VALUES (1, 0,'Home');
INSERT INTO CMS_PAGINE_DESC(ID_PAGINA,ID_LINGUA,DESCRIZIONE) VALUES (2, 0,'Dettaglio articolo');
INSERT INTO CMS_PAGINE_DESC(ID_PAGINA,ID_LINGUA,DESCRIZIONE) VALUES (1, 1,'Home');
INSERT INTO CMS_PAGINE_DESC(ID_PAGINA,ID_LINGUA,DESCRIZIONE) VALUES (2, 1,'View article');
COMMIT;

DROP SEQUENCE SEQ_CMS_PAGINE;
CREATE SEQUENCE SEQ_CMS_PAGINE START WITH 3 MAXVALUE 999999999999 MINVALUE 1 NOCYCLE NOCACHE NOORDER;
