--
-- Tables
--

CREATE TABLE CMS_LINGUE (
   ID_LINGUA          int(10)      NOT NULL,
   CODICE             varchar(10)  NOT NULL,
   DESCRIZIONE        varchar(50)  NOT NULL,
   ATTIVO             varchar(1)   NOT NULL,
   CONSTRAINT PK_CMS_LINGUE PRIMARY KEY (ID_LINGUA) );

CREATE TABLE CMS_TAG (
   ID_TAG             int(10)      NOT NULL,
   CODICE             varchar(50)  NOT NULL,
   ANTEPRIMA          varchar(1)   DEFAULT 'N',
   ORDINE             int(10)      DEFAULT 0,
   ATTIVO             varchar(1)   NOT NULL,
   CONSTRAINT PK_CMS_TAG PRIMARY KEY (ID_TAG) );

CREATE TABLE CMS_TAG_DESC (
   ID_TAG             int(10)      NOT NULL,
   ID_LINGUA          int(10)      NOT NULL,
   DESCRIZIONE        varchar(255) NOT NULL,
   CONSTRAINT PK_CMS_TAG_DESC PRIMARY KEY (ID_TAG, ID_LINGUA) );

CREATE TABLE CMS_ISTITUTI (
   ID_ISTITUTO        int(10)      NOT NULL,
   CODICE             varchar(50)  NOT NULL,
   DESCRIZIONE        varchar(255) NOT NULL,
   ATTIVO             varchar(1)   NOT NULL,
   CONSTRAINT PK_CMS_ISTITUTI PRIMARY KEY (ID_ISTITUTO) );

CREATE TABLE CMS_COMUNI (
   ID_COMUNE          int(10)      NOT NULL,
   COD_ISTAT          varchar(6)   NOT NULL,
   COD_FISCALE        varchar(4)   NOT NULL,
   DESCRIZIONE        varchar(255) NOT NULL,
   PROVINCIA          varchar(4),
   CONSTRAINT PK_CMS_COMUNI PRIMARY KEY (ID_COMUNE) );

CREATE TABLE CMS_TIPI_LUOGO (
   ID_TIPO_LUOGO      int(10)      NOT NULL,
   CODICE             varchar(255) NOT NULL,
   ATTIVO             varchar(1)   NOT NULL,
   CONSTRAINT PK_CMS_TIPI_LUOGO PRIMARY KEY (ID_TIPO_LUOGO) );
   
CREATE TABLE CMS_TIPI_LUOGO_DESC (
   ID_TIPO_LUOGO      int(10)      NOT NULL,
   ID_LINGUA          int(10)      NOT NULL,
   DESCRIZIONE        varchar(255),
   CONSTRAINT PK_CMS_TIPI_LUOGO_DESC PRIMARY KEY (ID_TIPO_LUOGO, ID_LINGUA),
   FOREIGN KEY (ID_LINGUA) REFERENCES CMS_LINGUE (ID_LINGUA) );
   
CREATE TABLE CMS_LUOGHI (
   ID_LUOGO           int(10)      NOT NULL,
   ID_TIPO_LUOGO      int(10)      NOT NULL,
   CODICE             varchar(50)  NOT NULL,
   DESCRIZIONE        varchar(255) NOT NULL,
   ID_COMUNE          int(10)      NOT NULL,
   INDIRIZZO          varchar(255),
   CAP                varchar(5),
   SITO_WEB           varchar(255),
   EMAIL              varchar(255),
   TEL_1              varchar(50),
   TEL_2              varchar(50),
   FAX                varchar(50),
   INFORMAZIONI       varchar(100),
   LATITUDINE         double,
   LONGITUDINE        double,
   RICERCA            varchar(255),
   ATTIVO             varchar(1)     NOT NULL,
   CONSTRAINT PK_CMS_LUOGHI PRIMARY KEY (ID_LUOGO),
   FOREIGN KEY (ID_TIPO_LUOGO) REFERENCES CMS_TIPI_LUOGO (ID_TIPO_LUOGO),
   FOREIGN KEY (ID_COMUNE) REFERENCES CMS_COMUNI (ID_COMUNE));

CREATE TABLE CMS_TIPI_AUTORE (
   ID_TIPO_AUTORE     int(10)      NOT NULL,
   DESCRIZIONE        varchar(255) NOT NULL,
   ATTIVO             varchar(1)   NOT NULL,
   CONSTRAINT PK_CMS_TIPI_AUTORE PRIMARY KEY (ID_TIPO_AUTORE) );

CREATE TABLE CMS_TIPI_CONTENUTO (
   ID_TIPO_CONTENUTO  int(10)      NOT NULL,
   DESCRIZIONE        varchar(255) NOT NULL,
   ATTIVO             varchar(1)   NOT NULL,
   CONSTRAINT PK_CMS_TIPI_CONTENUTO PRIMARY KEY (ID_TIPO_CONTENUTO) );

CREATE TABLE CMS_TIPI_UTENTE (
   ID_TIPO_UTENTE     int(10)      NOT NULL,
   DESCRIZIONE        varchar(255) NOT NULL,
   ATTIVO             varchar(1)   NOT NULL,
   CONSTRAINT PK_CMS_TIPI_UTENTE PRIMARY KEY (ID_TIPO_UTENTE) );

CREATE TABLE CMS_AUTORI (
   ID_AUTORE          int(10)      NOT NULL,
   ID_TIPO_AUTORE     int(10)      NOT NULL,
   COGNOME            varchar(50)  NOT NULL,
   NOME               varchar(50)  NOT NULL,
   SESSO              varchar(1),
   DATA_NASCITA       datetime,
   TITOLO             varchar(50),
   TELEFONO           varchar(50),
   CELLULARE          varchar(50),
   EMAIL              varchar(100),
   NOTE               text,
   CONSTRAINT PK_CMS_AUTORI PRIMARY KEY (ID_AUTORE),
   FOREIGN KEY (ID_TIPO_AUTORE) REFERENCES CMS_TIPI_AUTORE (ID_TIPO_AUTORE) );

CREATE TABLE CMS_UTENTI (
   ID_UTENTE          int(10)      NOT NULL,
   USERNAME           varchar(50)  NOT NULL,
   PASSWORD           varchar(50)  NOT NULL,
   ID_TIPO_UTENTE     int(10)      NOT NULL,
   COGNOME            varchar(50),
   NOME               varchar(50),
   SESSO              varchar(1),
   DATA_NASCITA       datetime,
   PROFESSIONE        varchar(50),
   CITTA              varchar(50),
   EMAIL              varchar(100),
   ATTIVO             varchar(1)   NOT NULL,
   DT_INS             datetime     NOT NULL,
   CONSTRAINT PK_CMS_UTENTI PRIMARY KEY (ID_UTENTE),
   FOREIGN KEY (ID_TIPO_UTENTE) REFERENCES CMS_TIPI_UTENTE (ID_TIPO_UTENTE) );

CREATE TABLE CMS_RUOLI (
   ID_RUOLO           int(10)      NOT NULL,
   DESCRIZIONE        varchar(255) NOT NULL,
   ATTIVO             varchar(1)   NOT NULL,
   CONSTRAINT PK_CMS_RUOLI PRIMARY KEY (ID_RUOLO) );

CREATE TABLE CMS_CATEGORIE (
   ID_CATEGORIA       int(10)      NOT NULL,
   CODICE             varchar(255) NOT NULL,
   ATTIVO             varchar(1)   NOT NULL,
   CONSTRAINT PK_CMS_CATEGORIE PRIMARY KEY (ID_CATEGORIA) );

CREATE TABLE CMS_CATEGORIE_DESC (
   ID_CATEGORIA       int(10)      NOT NULL,
   ID_LINGUA          int(10)      NOT NULL,
   DESCRIZIONE        varchar(255),
   CONSTRAINT PK_CMS_CATEGORIE_DESC PRIMARY KEY (ID_CATEGORIA, ID_LINGUA),
   FOREIGN KEY (ID_LINGUA) REFERENCES CMS_LINGUE (ID_LINGUA) );
   
CREATE TABLE CMS_SOTTOCATEGORIE (
   ID_SOTTOCATEGORIA  int(10)      NOT NULL,
   ID_CATEGORIA       int(10)      NOT NULL,
   CODICE             varchar(255) NOT NULL,
   ATTIVO             varchar(1)   NOT NULL,
   CONSTRAINT PK_CMS_SOTTOCATEGORIE PRIMARY KEY (ID_SOTTOCATEGORIA),
   FOREIGN KEY (ID_CATEGORIA) REFERENCES CMS_CATEGORIE (ID_CATEGORIA) );

CREATE TABLE CMS_SOTTOCATEGORIE_DESC (
   ID_SOTTOCATEGORIA  int(10)      NOT NULL,
   ID_LINGUA          int(10)      NOT NULL,
   DESCRIZIONE        varchar(255),
   CONSTRAINT PK_CMS_SOTTOCATEGORIE_DESC PRIMARY KEY (ID_SOTTOCATEGORIA, ID_LINGUA),
   FOREIGN KEY (ID_LINGUA) REFERENCES CMS_LINGUE (ID_LINGUA) );

CREATE TABLE CMS_TIPI_ARTICOLO (
   ID_TIPO_ARTICOLO   int(10)      NOT NULL,
   CODICE             varchar(255) NOT NULL,
   ATTIVO             varchar(1)   NOT NULL,
   CONSTRAINT PK_CMS_TIPI_ARTICOLO PRIMARY KEY (ID_TIPO_ARTICOLO) );

CREATE TABLE CMS_TIPI_ARTICOLO_DESC (
   ID_TIPO_ARTICOLO   int(10)      NOT NULL,
   ID_LINGUA          int(10)      NOT NULL,
   DESCRIZIONE        varchar(255),
   CONSTRAINT PK_CMS_TIPI_ARTICOLO_DESC PRIMARY KEY (ID_TIPO_ARTICOLO, ID_LINGUA),
   FOREIGN KEY (ID_LINGUA) REFERENCES CMS_LINGUE (ID_LINGUA) );
   
CREATE TABLE CMS_ARTICOLI (
   ID_ARTICOLO        int(10)      NOT NULL,
   DESCRIZIONE        varchar(255) NOT NULL,
   DATA_ARTICOLO      datetime     NOT NULL,
   ID_CATEGORIA       int(10)      NOT NULL,
   ID_SOTTOCATEGORIA  int(10)      NOT NULL,
   ID_TIPO_ARTICOLO   int(10)      NOT NULL,
   ID_ISTITUTO        int(10)      NOT NULL,
   ID_LUOGO           int(10)      NOT NULL,
   ID_TIPO_UTENTE     int(10)      NOT NULL,
   ATTIVO             varchar(1)   NOT NULL,
   DT_INS             datetime     NOT NULL,
   UTE_INS            varchar(50)  NOT NULL,
   DT_AGG             datetime,
   UTE_AGG            varchar(50),
   PREF_POS           int(10)      DEFAULT 0,
   DT_POS             datetime,
   PREF_NEG           int(10)      DEFAULT 0,
   DT_NEG             datetime,
   CONSTRAINT PK_CMS_ARTICOLI PRIMARY KEY (ID_ARTICOLO),
   FOREIGN KEY (ID_CATEGORIA) REFERENCES CMS_CATEGORIE (ID_CATEGORIA),
   FOREIGN KEY (ID_SOTTOCATEGORIA) REFERENCES CMS_SOTTOCATEGORIE (ID_SOTTOCATEGORIA),
   FOREIGN KEY (ID_TIPO_ARTICOLO) REFERENCES CMS_TIPI_ARTICOLO (ID_TIPO_ARTICOLO),
   FOREIGN KEY (ID_ISTITUTO) REFERENCES CMS_ISTITUTI (ID_ISTITUTO),
   FOREIGN KEY (ID_LUOGO) REFERENCES CMS_LUOGHI (ID_LUOGO),
   FOREIGN KEY (ID_TIPO_UTENTE) REFERENCES CMS_TIPI_UTENTE (ID_TIPO_UTENTE) );

CREATE TABLE CMS_ARTICOLI_AUT (
   ID_ARTICOLO        int(10)      NOT NULL,
   ID_AUTORE          int(10)      NOT NULL,
   ID_RUOLO           int(10)      NOT NULL,
   CONSTRAINT PK_CMS_ARTICOLI_AUT PRIMARY KEY (ID_ARTICOLO, ID_AUTORE),
   FOREIGN KEY (ID_AUTORE) REFERENCES CMS_AUTORI (ID_AUTORE),
   FOREIGN KEY (ID_RUOLO) REFERENCES CMS_RUOLI (ID_RUOLO) );

CREATE TABLE CMS_ARTICOLI_LUOGHI (
   ID_ARTICOLO        int(10)      NOT NULL,
   ID_LUOGO           int(10)      NOT NULL,
   ORDINE             int(10)      NOT NULL,
   DESCRIZIONE        varchar(255),
   CONSTRAINT PK_CMS_ARTICOLI_LUOGHI PRIMARY KEY (ID_ARTICOLO, ID_LUOGO),
   FOREIGN KEY (ID_LUOGO) REFERENCES CMS_LUOGHI (ID_LUOGO) );

CREATE TABLE CMS_ARTICOLI_CONT (
   ID_ARTICOLO        int(10)      NOT NULL,
   ID_LINGUA          int(10)      NOT NULL,
   TITOLO             varchar(255),
   SPECIFICA          varchar(255),
   ABSTRACT           text,
   TESTO              text,
   TESTO2             text,
   TESTO3             text,
   NOTE               text,
   RIFERIMENTI        text,
   KEYWORDS           text,
   CONSTRAINT PK_CMS_ARTICOLI_CONT PRIMARY KEY (ID_ARTICOLO, ID_LINGUA),
   FOREIGN KEY (ID_LINGUA)   REFERENCES CMS_LINGUE   (ID_LINGUA),
   FOREIGN KEY (ID_ARTICOLO) REFERENCES CMS_ARTICOLI (ID_ARTICOLO));
   
CREATE TABLE CMS_ARTICOLI_MULT (
   ID_MULTIMEDIA      int(10)      NOT NULL,
   ID_LINGUA          int(10)      NOT NULL,
   ID_TIPO_CONTENUTO  int(10)      NOT NULL,
   URL_FILE           varchar(255) NOT NULL,
   ID_ARTICOLO        int(10)      NOT NULL,
   ORDINE             int(10)      NOT NULL,
   DESCRIZIONE        text,
   CONSTRAINT PK_CMS_ARTICOLI_MULT PRIMARY KEY (ID_MULTIMEDIA),
   FOREIGN KEY (ID_LINGUA)   REFERENCES CMS_LINGUE (ID_LINGUA),
   FOREIGN KEY (ID_TIPO_CONTENUTO) REFERENCES CMS_TIPI_CONTENUTO (ID_TIPO_CONTENUTO),
   FOREIGN KEY (ID_ARTICOLO) REFERENCES CMS_ARTICOLI (ID_ARTICOLO));

CREATE TABLE CMS_ARTICOLI_TAG (
   ID_ARTICOLO        int(10)      NOT NULL,
   ID_TAG             int(10)      NOT NULL,
   DESCRIZIONE        varchar(255),
   CONSTRAINT PK_CMS_ARTICOLI_TAG PRIMARY KEY (ID_ARTICOLO, ID_TAG),
   FOREIGN KEY (ID_ARTICOLO) REFERENCES CMS_ARTICOLI (ID_ARTICOLO),
   FOREIGN KEY (ID_TAG)      REFERENCES CMS_TAG      (ID_TAG) );
   
CREATE TABLE CMS_ARTICOLI_CORR (
   ID_ARTICOLO        int(10)      NOT NULL,
   ID_ARTICOLO_CORR   int(10)      NOT NULL,
   ORDINE             int(10)      NOT NULL,
   CONSTRAINT PK_CMS_ARTICOLI_CORR PRIMARY KEY (ID_ARTICOLO, ID_ARTICOLO_CORR),
   FOREIGN KEY (ID_ARTICOLO)      REFERENCES CMS_ARTICOLI (ID_ARTICOLO),
   FOREIGN KEY (ID_ARTICOLO_CORR) REFERENCES CMS_ARTICOLI (ID_ARTICOLO) );

CREATE TABLE CMS_ARTICOLI_COMP (
   ID_ARTICOLO        int(10)      NOT NULL,
   ID_ARTICOLO_COMP   int(10)      NOT NULL,
   ORDINE             int(10)      NOT NULL,
   CONSTRAINT PK_CMS_ARTICOLI_COMP PRIMARY KEY (ID_ARTICOLO, ID_ARTICOLO_COMP),
   FOREIGN KEY (ID_ARTICOLO)      REFERENCES CMS_ARTICOLI (ID_ARTICOLO),
   FOREIGN KEY (ID_ARTICOLO_COMP) REFERENCES CMS_ARTICOLI (ID_ARTICOLO) );

CREATE TABLE CMS_ARTICOLI_PREZZI (
   ID_ARTICOLO        int(10)      NOT NULL,
   ID_LINGUA          int(10)      NOT NULL,
   ORDINE             int(10)      NOT NULL,
   CODICE             varchar(50),
   DESCRIZIONE        varchar(255),
   PREZZO             double, 
   SCONTO             int(3),
   SCONTATO           double,
   ACCONTO            double,
   PROMOZIONE         varchar(1),
   CONSTRAINT PK_CMS_ARTICOLI_PREZZI PRIMARY KEY (ID_ARTICOLO, ID_LINGUA, ORDINE),
   FOREIGN KEY (ID_LINGUA)   REFERENCES CMS_LINGUE   (ID_LINGUA),
   FOREIGN KEY (ID_ARTICOLO) REFERENCES CMS_ARTICOLI (ID_ARTICOLO));
   
CREATE TABLE CMS_TIPI_PAGINA (
   ID_TIPO_PAGINA     int(10)      NOT NULL,
   DESCRIZIONE        varchar(255) NOT NULL,
   ATTIVO             varchar(1)   NOT NULL,
   CONSTRAINT PK_CMS_TIPI_PAGINA PRIMARY KEY (ID_TIPO_PAGINA) );

CREATE TABLE CMS_PAGINE (
   ID_PAGINA          int(10)      NOT NULL,
   ID_TIPO_PAGINA     int(10)      NOT NULL,
   CODICE             varchar(50)  NOT NULL,
   ID_CATEGORIA       int(10)      NOT NULL,
   ID_SOTTOCATEGORIA  int(10)      NOT NULL,
   ID_TIPO_ARTICOLO   int(10)      NOT NULL,
   ORDINE             int(10)      NOT NULL,
   RIGHE              int(10),
   COLONNE            int(10),
   VISTA              int(10),
   ATTIVO             varchar(1)   NOT NULL,
   CONSTRAINT PK_CMS_PAGINE PRIMARY KEY (ID_PAGINA),
   FOREIGN KEY (ID_CATEGORIA)      REFERENCES CMS_CATEGORIE (ID_CATEGORIA),
   FOREIGN KEY (ID_SOTTOCATEGORIA) REFERENCES CMS_SOTTOCATEGORIE (ID_SOTTOCATEGORIA),
   FOREIGN KEY (ID_TIPO_ARTICOLO)  REFERENCES CMS_TIPI_ARTICOLO (ID_TIPO_ARTICOLO),
   FOREIGN KEY (ID_TIPO_PAGINA)    REFERENCES CMS_TIPI_PAGINA (ID_TIPO_PAGINA) );
   
CREATE TABLE CMS_PAGINE_DESC (
   ID_PAGINA          int(10)      NOT NULL,
   ID_LINGUA          int(10)      NOT NULL,
   DESCRIZIONE        varchar(255),
   CONSTRAINT PK_CMS_PAGINE_DESC PRIMARY KEY (ID_PAGINA, ID_LINGUA),
   FOREIGN KEY (ID_PAGINA) REFERENCES CMS_PAGINE (ID_PAGINA),
   FOREIGN KEY (ID_LINGUA) REFERENCES CMS_LINGUE (ID_LINGUA) );
   
CREATE TABLE CMS_PAGINE_ARTICOLI (
   ID_PAGINA          int(10)      NOT NULL,
   ID_ARTICOLO        int(10)      NOT NULL,
   ORDINE             int(10)      NOT NULL,
   CONSTRAINT PK_CMS_PAGINE_ARTICOLI PRIMARY KEY (ID_PAGINA, ID_ARTICOLO),
   FOREIGN KEY (ID_PAGINA)   REFERENCES CMS_PAGINE (ID_PAGINA),
   FOREIGN KEY (ID_ARTICOLO) REFERENCES CMS_ARTICOLI (ID_ARTICOLO) );

CREATE TABLE CMS_PAGINE_COMP (
   ID_PAGINA          int(10)      NOT NULL,
   ID_PAGINA_COMP     int(10)      NOT NULL,
   ORDINE             int(10)      NOT NULL,
   CONSTRAINT PK_CMS_PAGINE_COMP PRIMARY KEY (ID_PAGINA, ID_PAGINA_COMP),
   FOREIGN KEY (ID_PAGINA)      REFERENCES CMS_PAGINE (ID_PAGINA),
   FOREIGN KEY (ID_PAGINA_COMP) REFERENCES CMS_PAGINE (ID_PAGINA) );

CREATE TABLE CMS_LOG_VISITE (
   ID_ARTICOLO        int(10)      NOT NULL,
   DT_VISITA          datetime     NOT NULL,
   ID_UTENTE          int(10)      NOT NULL
);

CREATE TABLE CMS_PROGRESSIVI (
   CODICE             varchar(50)  NOT NULL,
   VALORE             int(10)      NOT NULL,
   CONSTRAINT PK_CMS_PROGRESSIVI PRIMARY KEY (CODICE) );

-- Indexes

CREATE INDEX IDX_AUTORI_COGNOME  ON CMS_AUTORI(COGNOME);
CREATE INDEX IDX_UTENTI_USERNAME ON CMS_UTENTI(USERNAME);
CREATE INDEX IDX_TAG_CODICE      ON CMS_TAG(CODICE);
CREATE INDEX IDX_LUOGHI_COM_CAP  ON CMS_LUOGHI(ID_COMUNE, CAP);

-- Sequences

INSERT INTO CMS_PROGRESSIVI VALUES('SEQ_CMS_LINGUE',         0);
INSERT INTO CMS_PROGRESSIVI VALUES('SEQ_CMS_TAG',            0);
INSERT INTO CMS_PROGRESSIVI VALUES('SEQ_CMS_CATEGORIE',      0);
INSERT INTO CMS_PROGRESSIVI VALUES('SEQ_CMS_SOTTOCATEGORIE', 0);
INSERT INTO CMS_PROGRESSIVI VALUES('SEQ_CMS_ISTITUTI',       0);
INSERT INTO CMS_PROGRESSIVI VALUES('SEQ_CMS_COMUNI',         0);
INSERT INTO CMS_PROGRESSIVI VALUES('SEQ_CMS_LUOGHI',         0);
INSERT INTO CMS_PROGRESSIVI VALUES('SEQ_CMS_RUOLI',          0);
INSERT INTO CMS_PROGRESSIVI VALUES('SEQ_CMS_UTENTI',         0);
INSERT INTO CMS_PROGRESSIVI VALUES('SEQ_CMS_AUTORI',         0);
INSERT INTO CMS_PROGRESSIVI VALUES('SEQ_CMS_ARTICOLI',       0);
INSERT INTO CMS_PROGRESSIVI VALUES('SEQ_CMS_ARTICOLI_MULT',  0);
INSERT INTO CMS_PROGRESSIVI VALUES('SEQ_CMS_PAGINE',         0);
INSERT INTO CMS_PROGRESSIVI VALUES('SEQ_CMS_TIPI_UTENTE',    0);
INSERT INTO CMS_PROGRESSIVI VALUES('SEQ_CMS_TIPI_ARTICOLO',  0);
INSERT INTO CMS_PROGRESSIVI VALUES('SEQ_CMS_TIPI_LUOGO',     0);
INSERT INTO CMS_PROGRESSIVI VALUES('SEQ_CMS_TIPI_AUTORE',    0);
INSERT INTO CMS_PROGRESSIVI VALUES('SEQ_CMS_TIPI_CONTENUTO', 0);
INSERT INTO CMS_PROGRESSIVI VALUES('SEQ_CMS_TIPI_PAGINA',    0);

